### PR TITLE
xtypes for DALI-1.2

### PR DESCRIPTION
**Pull request by pdowler**
shape
multipolygon
moc

### CODE REVIEW

**Comment by mbtaylor** [comment]
* The "Multi-Polygon" section starts *"MOC (Multi Order Coverage) values..."* - I think that's a typo for *"Multiple polygon values..."* or similar.
* I get nervous about mandating `arraysize="*"`; in practice it's very likely that an unconstrained size will be used, but it doesn't seem right to forbid providing a fixed or limited length for these character arrays.  Can we just say something like *"The FIELD or PARAM must be string-valued and have xtype="moc"*?  That would also allow `datatype="unicodeChar"` - again, not necessarily something we want to encourage, but this doesn't seem like the place to ban such usage.
* Some of the lines in this commit are rather long, can you introduce some line breaks for ease of diffing?
* I have done some prototyping; my preference is for 2 NaNs rather than 1 to separate polygons in multipolygon.  For one thing, it means that if you see an odd number of values you can immediately issue a "wrong size array" error message.  But I can cope either way.

**Comment by mbtaylor** [comment]
The wording for `shape`:
> The value is a polymorphic shape made up of a type label (equivalent to an existing xtype: `circle` or `polygon`)

suggests but doesn't quite make explicit that only `circle` and `polygon` are permissible shapes here.  Is that the intention?  Why not allow `multipolygon` (and `moc`?) as well?

**Comment by pdowler** [comment]
I have tentatively added both moc and multipolygon to the list of shapes explicitly for now, but I'm, not sure about that one. The use cases only really needed circle and polygon or multipolygon... I don't think there is a use case for a list of shapes that could include moc(s) in with the other shapes. 

On the implementation side (say in TAP upload) the recipient of a column of shape values should be able to put all the values into a database column and perform at least an approximate spatial query. That seems unlikely to work if the back end supports polygon and the value is a moc (because mocs are considerably more complex). I'd prefer to be conservative and leave moc off the list for now...

**Comment by mbtaylor** [comment]
OK, adding multipolygon but not MOC sounds reasonable.  I can't think of a compelling MOC + other-shape use case either.

**Review by mbtaylor — APPROVED** [review]
Looks OK to me.

**Pull request merged**
